name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Test backend
        run: |
          cd backend
          python -m pytest --version || echo "No tests configured"
          
      - name: Deploy to Render
        run: |
          echo "Backend deployment to Render will be triggered automatically"
          echo "Render webhook URL: ${{ secrets.RENDER_DEPLOY_HOOK }}"
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"