name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: [main]
    paths: ['frontend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Debug - Check file structure
        run: |
          cd frontend
          echo "=== Current directory ==="
          pwd
          echo "=== Listing all files ==="
          ls -la
          echo "=== Checking public directory ==="
          ls -la public/
          echo "=== Checking src directory ==="
          ls -la src/
          echo "=== Checking if index.html exists ==="
          test -f public/index.html && echo "index.html EXISTS" || echo "index.html MISSING"
          
      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.BACKEND_URL }}
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: teto-egen-test
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
